### ISSUE TITLE
$% doesn't error on duplicate stems

### ISSUE THREAD

**Issue by ohAitch** [urbit/arvo#296]
This shouldn't compile:

```
> $%({$a @} {$a @ @})
<1.ziw {* {him/@p our/@p now/@da eny/@uvJ} $~ <288.euk 42.dit 409.spy 110.xht 1.ztu $151>}>
```

Because the purpose of `$%` "kelp" is to discriminate orthogonal cases, and result is not a proper kelp:

```
> ($%({$a @} {$a @ @}) %a 1 1)
[%a 0]
```

HT @Fang- for demonstrating this in ~talkbot

**Comment by chc4** [comment]
I looked into it a bit, and the parsing of a `$%` (`%book`) is just a generic exps parser. It builds the actual `%kelp` by looping over the list of expressions, but that happens in `++boil` instead of parsing, so it wouldn't have a good error message (no line/col numbering...)

Is there a proper way to do this, or would just `dup-kelp-case %foo` in a stack trace be good enough.

**Comment by joemfb** [comment]
I took a look at this too, and realized I didn't know much about `$%` ... I've only ever seen it used with a list of `:bank` (`$:`/`{}`) molds, so I was surprised to see the `$fern` head case.

As near as I can tell, if the first "page" isn't a `$leaf` or `:bank`, the mold becomes a `:pick` between that first page and the `:book` itself. The compiler crashes (`book-foul`) if any other page isn't a `$leaf` or `:bank`.

`$%(@ud {$foo $~} {$bar ^})` is equivalent to `$?(@ud $%({$foo $~} {$bar ^}))`

Is this description of `:book` accurate, or are there other valid page molds?

As @chc4 said, the parser doesn't enforce any of this. Should it? It seems straightforward enough to write something `++wisp` that enforces these requirements.

The `:book` mold in that docs is `{$book p/(list {{aura @} moss})}`; is that what it should be in the actual implementation?

//cc @cgyarvin

**Comment by ohAitch** [comment]
It's definitely what I had expected it to be; I can see the upsides of
having a type you're inheriting from, esp if it's another book, though I
think my preferred solution there would be to make regular-form $? fixed
arity(of 2) so you can just do  $? base-case $% etc ==  without extra
indentation creep.

**Comment by ohAitch** [comment]
The mold from the docs* is definitely what I had expected it to be

**Comment by joemfb** [comment]
I guess that still leaves the question of how to represent pages that are *just* leaf molds:

```
> (ream '$%({$foo $~} $10)')
[%book p=~[[%bank p=~[[%leaf p=[p=%tas q=7.303.014]] [%leaf p=[p=%n q=0]]]] [%leaf p=[p=%ud q=10]]]]
```

`{$book p/(list {{aura @} (unit moss)})}` would cover it, but it seems a little messy...

**Comment by ohAitch** [comment]
My expectation of a $% is that it nests in {@ *}, so encode the leaf as a
stem i.e. {$10 $~} or have a  $@ ?(leaves...)  $% pages... ==

**Comment by joemfb** [comment]
My mistake! I thought I had tested that in the `:dojo`, but I had only parsed it:

```
> ~(boil ap (ream '$%({$foo $~} $10)'))
%book-foul
```

**Comment by cgyarvin** [comment]
Yuck.  It's difficult to say anything very simple about this system -- it
is not terribly broken, but it is generally rough and could benefit from a
really comprehensive redesign.  I hesitate to tweak it, unless anyone has
any really brilliant ideas for tweaks.

**Comment by ohAitch** [comment]
Iirc you wanted the parser to be simpler at the expense of slightly more
confusing errors, similarly to the 151 translation; my brilliant idea is to
bring back the twig/tile parser distinction even if you retain the split
syntax, and slightly less ambitious brilliant idea is to duplicate
++exps/++hank for :book specific usage, sticking in a (sear) that checks
for cell-atom-noun-ness.

**Comment by cgyarvin** [comment]
I think this system is complex enough that it can't be solved by shots from
the hip.  It's not perfect but it's not killing us.

Often the best way to fix something is not to fix it.  That way, it
eventually gets actually fixed by a well-aimed shot, rather than half-fixed
by a shot from the hip.

**Comment by ohAitch** [comment]
It's more like necromancy from the hip really, but point taken.

This leaves the question of the first-item behavior, do you remember why
it's special cased to not necessarily be a page?

**Comment by belisarius222** [comment]
Confirmed this still compiles on Hoon %143, so this issue is still relevant.

**Comment by Fang-** [comment]
Re-opening because the closing PR got reverted.
