### ISSUE TITLE
+moon is failing

### ISSUE THREAD

**Issue by frodwith** [urbit/arvo#3]
> +moon
    /~pormev-taglyn/home/~2016.2.16..21.37.07..74d7/arvo/ford:<[1.303 24].[1.303 38]>
    nest-fail
    -want.[[now=@da eny=@uvI bec=[p=@p q=@tas r=?([%tas p=@tas] [%da p=@da] [%ud p=@ud])]] %~]
    -have.[[now=@da eny=@uvI bec=[p=@p q=@tas r=?([%tas p=@tas] [%da p=@da] [%ud p=@ud])]] %~ %~]

**Comment by juped** [comment]
Incomplete 151ization. Will get the fix in in a bit. Thanks!

**Comment by juped** [comment]
Fixed in 6c8d537

**Comment by frodwith** [comment]
Still failing for me, although in a very different way:

    ~pormev-taglyn:dojo> +moonlost: [97 '~pormev-taglyn' %tick '~2016.2.18..01.46.21..bdf4' '~disrev-nopdel-pormev-taglyn' 0]
    > +moon
    /~pormev-taglyn/home/0/gen/moon:<[13 1].[17 37]>
    /~pormev-taglyn/home/0/gen/moon:<[14 1].[17 37]>
    /~pormev-taglyn/home/0/gen/moon:<[15 1].[17 37]>
    /~pormev-taglyn/home/0/gen/moon:<[16 1].[17 37]>
    /~pormev-taglyn/home/0/gen/moon:<[16 5].[16 68]>
    /~pormev-taglyn/home/0/gen/moon:<[16 9].[16 68]>
